<a href="https://colab.research.google.com/github/tejasreerani/Uber-Eats-Bangalore-Restaurant-Intelligence-Decision-Support-Systems/blob/main/01_Uber_Eats_Restaurant_Intelligence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import sqlite3

In [ ]:
# Read CSV file
df=pd.read_csv('Uber_Eats_data.csv')
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

In [ ]:
# Connect to sqlite3 database
conn=sqlite3.connect('Uber_Eats.db')
mycursor=conn.cursor()

In [ ]:
# Remove duplicates & data cleaning

df=df.drop_duplicates()

In [ ]:
# Cleaning the data

def clean_rate(x):
    if isinstance(x, str) and "/" in x:
        return float(x.split("/")[0])
    else:
        return None

df.loc[:, "rate"] = df["rate"].apply(clean_rate)

In [ ]:
df.columns = ['name', 'online_order', 'book_table', 'rate', 'votes', 'phone', 'location', 'rest_type', 'dish_liked', 'cuisines', 'approx_cost', 'listed_type', 'listed_city']
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines', 'approx_cost',
       'listed_type', 'listed_city'],
      dtype='object')

In [ ]:
data=df.values.tolist()
data

[['Jalsa',
  'Yes',
  'Yes',
  4.1,
  775,
  '080 42297555\r\n+91 9743772233',
  'Banashankari',
  'Casual Dining',
  'Pasta, Lunch Buffet, Masala Papad, Paneer Lajawab, Tomato Shorba, Dum Biryani, Sweet Corn Soup',
  'North Indian, Mughlai, Chinese',
  '800',
  'Buffet',
  'Banashankari'],
 ['Spice Elephant',
  'Yes',
  'No',
  4.1,
  787,
  '080 41714161',
  'Banashankari',
  'Casual Dining',
  'Momos, Lunch Buffet, Chocolate Nirvana, Thai Green Curry, Paneer Tikka, Dum Biryani, Chicken Biryani',
  'Chinese, North Indian, Thai',
  '800',
  'Buffet',
  'Banashankari'],
 ['San Churro Cafe',
  'Yes',
  'No',
  3.8,
  918,
  '+91 9663487993',
  'Banashankari',
  'Cafe, Casual Dining',
  'Churros, Cannelloni, Minestrone Soup, Hot Chocolate, Pink Sauce Pasta, Salsa, Veg Supreme Pizza',
  'Cafe, Mexican, Italian',
  '800',
  'Buffet',
  'Banashankari'],
 ['Addhuri Udupi Bhojana',
  'No',
  'No',
  3.7,
  88,
  '+91 9620009302',
  'Banashankari',
  'Quick Bites',
  'Masala Dosa',
  'South Indian, North Indian',
  '300',
  'Buffet',
  'Banashankari'],
 ['Grand Village',
  'No',
  'No',
  3.8,
  166,
  '+91 8026612447\r\n+91 9901210005',
  'Basavanagudi',
  'Casual Dining',
  'Panipuri, Gol Gappe',
  'North Indian, Rajasthani',
  '600',
  'Buffet',
  'Banashankari'],
 ['Timepass Dinner',
  'Yes',
  'No',
  3.8,
  286,
  '+91 9980040002\r\n+91 9980063005',
  'Basavanagudi',
  'Casual Dining',
  'Onion Rings, Pasta, Kadhai Paneer, Salads, Salad, Roti, Jeera Rice',
  'North Indian',
  '600',
  'Buffet',
  'Banashankari'],
 ['Onesta',
  'Yes',
  'Yes',
  4.6,
  2556,
  '080 48653961\r\n080 48655715',
  'Banashankari',
  'Casual Dining, Cafe',
  'Farmhouse Pizza, Chocolate Banana, Virgin Mojito, Pasta, Paneer Tikka, Lime Soda, Prawn Pizza',
  'Pizza, Cafe, Italian',
  '600',
  'Cafes',
  'Banashankari'],
 ['Penthouse Cafe',
  'Yes',
  'No',
  4.0,
  324,
  '+91 8884135549\r\n+91 9449449316',
  'Banashankari',
  'Cafe',
  'Pizza, Mocktails, Coffee, Nachos, Salad, Pasta, Sandwiches',
  'Cafe, Italian, Continental',
  '700',
  'Cafes',
  'Banashankari'],
 ['Smacznego',
  'Yes',
  'No',
  4.2,
  504,
  '+91 9945230807\r\n+91 9743804471',
  'Banashankari',
  'Cafe',
  'Waffles, Pasta, Coleslaw Sandwich, Choco Waffle, Tacos, Momos, Cheese Nachos',
  'Cafe, Mexican, Italian, Momos, Beverages',
  '550',
  'Cafes',
  'Banashankari'],
 ['CafÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â\x83Ã\x83Â\x83Ã\x82Â\x82Ã\x83Â\x82Ã\x82Â© Down The Alley',
  'Yes',
  'No',
  4.1,
  402,
  '080 26724489\r\n+91 7406048982',
  'Banashankari',
  'Cafe',
  'Waffles, Pasta, Crispy Chicken, Honey Chilli Chicken, Sandwich, Coffee, Crepe',
  'Cafe',
  '500',
  'Cafes',
  'Banashankari'],
 ['Cafe Shuffle',
  'Yes',
  'Yes',
  4.2,
  150,
  '+91 9742166777',
  'Banashankari',
  'Cafe',
  'Mocktails, Peri Fries, Lasagne, Pizza, Chicken Bbq Wings, Virgin Mojito, Nachos',
  'Cafe, Italian, Continental',
  '600',
  'Cafes',
  'Banashankari'],
 ['The Coffee Shack',
  'Yes',
  'Yes',
  4.2,
  164,
  '+91 9731644212',
  'Banashankari',
  'Cafe',
  'Coffee, Spaghetti, Pancakes, Nachos, Pasta, Sandwich, Garlic Bread',
  'Cafe, Chinese, Continental, Italian',
  '500',
  'Cafes',
  'Banashankari'],
 ['Caf-Eleven',
  'No',
  'No',
  4.0,
  424,
  '080 49577715',
  'Banashankari',
  'Cafe',
  'Sandwich, Omelette, Ice Tea, Virgin Mojito, Hot Chocolate, Pasta Arrabiata, Hazelnut Cappuccino',
  'Cafe, Continental',
  '450',
  'Cafes',
  'Banashankari'],
 ['San Churro Cafe',
  'Yes',
  'No',
  3.8,
  918,
  '+91 9663487993',
  'Banashankari',
  'Cafe, Casual Dining',
  'Churros, Cannelloni, Minestrone Soup, Hot Chocolate, Pink Sauce Pasta, Salsa, Veg Supreme Pizza',
  'Cafe, Mexican, Italian',
  '800',
  'Cafes',
  'Banashankari'],
 ['Cafe Vivacity',
  'Yes',
  'No',
  3.8,
  90,
  '080 26768182\r\n+91 9845704455',
  'Banashankari',
  'Cafe',
  'Garlic Bread, Burgers, Sandwiches, Pizza, Hot Chocolate Fudge, Waffles, Potato Wedges',
  'Cafe',
  '650',
  'Cafes',
  'Banashankari'],
 ['Catch-up-ino',
  'Yes',
  'No',
  3.9,
  133,
  '+91 9972988038\r\n+91 9900121238',
  'Banashankari',
  'Cafe',
  'Momos, Mushroom Bruschettas, Jalapeno Cheeseballs, Pasta, Red Velvet Shake, Red Velvet Milkshake, Maggi',
  'Cafe, Fast Food, Continental, Chinese, Momos',
  '800',
  'Cafes',
  'Banashankari'],
 ["Kirthi's Biryani",
  'Yes',
  'No',
  3.8,
  144,
  '080 26711554\r\n+91 9741406338',
  'Banashankari',
  'Cafe',
  'Pasta, Gelato, Garlic Bread, Mojito, Nachos, Paneer Pizza, Mocktails',
  'Chinese, Cafe, Italian',
  '700',
  'Cafes',
  'Banashankari'],
 ['T3H Cafe',
  'No',
  'No',
  3.9,
  93,
  '+91 8884726600',
  'Banashankari',
  'Cafe',
  'Cheese Maggi, Peri Peri Fries, Pasta Arrabiata',
  'Cafe, Italian, American',
  '300',
  'Cafes',
  'Banashankari'],
 ['The Vintage Cafe',
  'Yes',
  'No',
  3.0,
  62,
  '+91 9880016665\r\n+91 8217311687',
  'Banashankari',
  'Cafe',
  'Burgers, Caramel Milkshake, Iced Coffee, Iced Tea',
  'Cafe, French, North Indian',
  '400',
  'Cafes',
  'Banashankari'],
 ['Woodee Pizza',
  'Yes',
  'No',
  3.7,
  180,
  '+91 7406822844',
  'Banashankari',
  'Cafe',
  'Pizza, Garlic Bread',
  'Cafe, Pizza, Fast Food, Beverages',
  '500',
  'Cafes',
  'Banashankari'],
 ['My Tea House',
  'Yes',
  'No',
  3.6,
  62,
  '080 65975430\r\n+91 7337733798',
  'Banashankari',
  'Quick Bites, Cafe',
  'Pasta, Iced Tea',
  'Italian, Fast Food, Cafe, European',
  '600',
  'Cafes',
  'Banashankari'],
 ["Srinathji's Cafe",
  'No',
  'No',
  3.8,
  148,
  '080 26600704\r\n+91 9342593424',
  'Basavanagudi',
  'Casual Dining, Cafe',
  'Paratha, Sandwich, Chilli Idli, Noodles, Sandwiches, Lime Soda',
  'North Indian, Cafe, Chinese, Fast Food',
  '550',
  'Cafes',
  'Banashankari'],
 ['Redberrys',
  'Yes',
  'No',
  4.0,
  219,
  '+91 9148421256',
  'Basavanagudi',
  'Cafe',
  'Pizza, Fries, Anjeer Ice Cream, Sandwiches, Gelato, Burgers, Kesar Badam',
  'Cafe, Italian',
  '600',
  'Cafes',
  'Banashankari'],
 ['Foodiction',
  'Yes',
  'No',
  2.8,
  506,
  '+91 9916107070',
  'Banashankari',
  'Quick Bites',
  'Burgers, Lassi, Chicken Grill, Naan, Momos, Chicken Burger, Biryani',
  'North Indian, Fast Food, Chinese, Burger',
  '500',
  'Delivery',
  'Banashankari'],
 ['Ovenstory Pizza',
  'Yes',
  'No',
  3.9,
  172,
  '+91 7738383000',
  'Banashankari',
  'Delivery',
  'Paneer Tikka, Garlic Bread, Thin Crust Pizza, Falafel, Veggie Pizza',
  'Pizza',
  '750',
  'Delivery',
  'Banashankari'],
 ['Faasos',
  'Yes',
  'No',
  4.2,
  415,
  '+91 7700020020',
  'Banashankari',
  'Quick Bites',
  'Rolls, Veggie Wrap, Chocolate Fantasy, Rice Bowls, Chicken Rice, Paneer Makhanwala, Chicken Tikka Wrap',
  'North Indian, Biryani, Fast Food',
  '500',
  'Delivery',
  'Banashankari'],
 ['Behrouz Biryani',
  'Yes',
  'No',
  3.9,
  230,
  '+91 7022260661\r\n+91 7022260662',
  'Banashankari',
  'Delivery',
  'Raita, Gulab Jamun, Paneer Biryani, Vegetable Biryani, Gosht Dum Biryani, Chicken Biryani, Murgh Biryani',
  'Biryani',
  '650',
  'Delivery',
  'Banashankari'],
 ['Szechuan Dragon',
  'Yes',
  'No',
  4.2,
  1647,
  '00 919663567711\r\n+91 9916326323',
  'Banashankari',
  'Casual Dining',
  'Noodles, Momos, Veg Manchow Soup, Kung Pao Chicken, Chicken Lollipop, Chop Suey, Dragon Chicken',
  'Chinese, Thai, Momos',
  '600',
  'Delivery',
  'Banashankari'],
 ['Empire Restaurant',
  'Yes',
  'No',
  4.4,
  4884,
  '080 49653266',
  'Jayanagar',
  'Casual Dining',
  'Chicken Tikka Masala, Mutton Keema Dosa, Mutton Biryani, Raan Biryani, Brain Fry, Chicken Grill, Ghee Rice',
  'North Indian, Mughlai, South Indian, Chinese',
  '750',
  'Delivery',
  'Banashankari'],
 ['Chaatimes',
  'Yes',
  'No',
  3.8,
  133,
  '+91 8884232233',
  'Basavanagudi',
  'Quick Bites',
  'Dabeli, Faluda, Masala Poori, Sandwiches, Tokri Chaat, Pav Bhaji, Dahipuri',
  'Street Food, Fast Food',
  '200',
  'Delivery',
  'Banashankari'],
 ["McDonald's",
  'Yes',
  'No',
  3.9,
  286,
  '080 66000666\r\n080 42005285',
  'Banashankari',
  'Quick Bites',
  'Burgers, Fries, Hot Chocolate',
  'Burger, Fast Food',
  '500',
  'Delivery',
  'Banashankari'],
 ["Domino's Pizza",
  'Yes',
  'No',
  3.9,
  540,
  '080 26710070\r\n18602100000',
  'Banashankari',
  'Quick Bites',
  'Pane Pizza, Lava Cake, Pasta, Stuffed Garlic Bread, Chocolava Cake, Tacos',
  'Pizza, Fast Food',
  '800',
  'Delivery',
  'Banashankari'],
 ['Onesta',
  'Yes',
  'Yes',
  4.6,
  2556,
  '080 48653961\r\n080 48655715',
  'Banashankari',
  'Casual Dining, Cafe',
  'Farmhouse Pizza, Chocolate Banana, Virgin Mojito, Pasta, Paneer Tikka, Lime Soda, Prawn Pizza',
  'Pizza, Cafe, Italian',
  '600',
  'Delivery',
  'Banashankari'],
 ['Hotboxit',
  'No',
  'No',
  3.8,
  36,
  '+91 7026677677\r\n+91 7026577577',
  'Banashankari',
  'Delivery',
  'Prompt Service',
  'North Indian, Continental, Italian',
  '400',
  'Delivery',
  'Banashankari'],
 ['Kitchen Garden',
  'Yes',
  'No',
  3.6,
  244,
  '080 49652867',
  'Kumaraswamy Layout',
  'Quick Bites',
  'Biryani',
  'North Indian, Chinese',
  '300',
  'Delivery',
  'Banashankari'],
 ['Recipe',
  'Yes',
  'No',
  4.0,
  804,
  '+91 8043755256\r\n+91 9886073774',
  'Kumaraswamy Layout',
  'Casual Dining',
  'Butter Chicken, Noodles, Thali, Biryani',
  'North Indian, Chinese, Biryani, Rolls',
  '450',
  'Delivery',
  'Banashankari'],
 ['Beijing Bites',
  'Yes',
  'No',
  3.7,
  679,
  '080 28606888\r\n080 28606886',
  'Rajarajeshwari Nagar',
  'Casual Dining',
  'Momos, Dragon Chicken, Hakka Noodles, Chowmein, Chop Suey, Chilli Garlic Noodles, Garlic Rice',
  'Chinese, Thai',
  '850',
  'Delivery',
  'Banashankari'],
 ['Tasty Bytes',
  'Yes',
  'No',
  3.1,
  245,
  '+91 8553317408\r\n+91 7899687127',
  'Kumaraswamy Layout',
  'Quick Bites',
  'Paratha, Pasta',
  'North Indian, Chinese, Momos, Rolls',
  '300',
  'Delivery',
  'Banashankari'],
 ['Corner House Ice Cream',
  'No',
  'No',
  4.3,
  345,
  '080 26713965\r\n+91 9845444155',
  'Banashankari',
  'Dessert Parlor',
  'Hot Chocolate Fudge, Vanilla Ice Cream, Fudge Cake, Chocolate Mousse',
  'Ice Cream, Desserts',
  '400',
  'Delivery',
  'Banashankari'],
 ['Biryanis And More',
  'Yes',
  'No',
  4.0,
  618,
  '080 48542442\r\n+91 7337271771',
  'Jayanagar',
  'Casual Dining',
  'Prawn Biryani, Dragon Chicken, Chicken Boneless Biryani, Afghani Biryani, Mughlai Biryani, Paneer Tikka Biryani, Gongura Biryani',
  'Biryani, North Indian, Chinese, Andhra, South Indian',
  '750',
  'Delivery',
  'Banashankari'],
 ['Roving Feast',
  'No',
  'No',
  4.0,
  1047,
  '080 42024092\r\n080 42274242',
  'Banashankari',
  'Quick Bites',
  'Pasta, Momos, Rolls, Chicken Roll, Chilli Chicken, Paneer Roll, Spaghetti',
  'Italian, Continental, Fast Food, Chinese, Momos',
  '450',
  'Delivery',
  'Banashankari'],
 ['FreshMenu',
  'Yes',
  'No',
  3.9,
  627,
  '080 40424242',
  'Banashankari',
  'Delivery',
  'Salads, Sandwiches, Salad, Thai Rice, Pasta, Noodles, Pizza',
  'Healthy Food, Chinese, Biryani, North Indian, Continental, Salad, American, Burger',
  '450',
  'Delivery',
  'Banashankari'],
 ['Wamama',
  'Yes',
  'Yes',
  4.2,
  354,
  '+91 8042111599\r\n+91 8971818009',
  'Banashankari',
  'Casual Dining',
  'Sushi, Noodles, Wine, Khau Suey, Mocktails, Yakisoba, Spring Roll',
  'Asian, Korean, Indonesian, Japanese, Chinese, Thai, Momos',
  '800',
  'Delivery',
  'Banashankari'],
 ['Peppy Peppers',
  'No',
  'No',
  4.2,
  244,
  '+91 8042297555\r\n+91 7022455300',
  'Banashankari',
  'Casual Dining',
  'Pasta, Pepper Pizza, Paneer Pizza, Peppy Paneer, Nachos, Supreme Pizza, Manchow Soup',
  'Italian, North Indian, Mexican',
  '800',
  'Delivery',
  'Banashankari'],
 ['Goa 0 Km',
  'Yes',
  'Yes',
  3.6,
  163,
  '080 49653548',
  'Kumaraswamy Layout',
  'Casual Dining',
  'Sea Food, Crab Meat, Crab Soup, Fish Curry, Chicken Cafreal, Butter Naan, Butter Chicken',
  'Goan, Seafood, North Indian, Chinese, Biryani',
  '800',
  'Delivery',
  'Banashankari'],
 ['1947',
  'No',
  'Yes',
  4.0,
  808,
  '080 26791213\r\n+91 9739989446',
  'Banashankari',
  'Casual Dining',
  'Salads, Panneer Butter Masala, Rabri, Gajar Ka Halwa, Manchow Soup, Aam Panna, Tomato Basil Soup',
  'North Indian, Chinese',
  '850',
  'Delivery',
  'Banashankari'],
 ['Kabab Magic',
  'Yes',
  'No',
  4.1,
  1720,
  '080 26570381',
  'Basavanagudi',
  'Quick Bites',
  'Grape Juice, Chicken Grill, Chicken Tikka Roll, Shawarma Roll, Chicken Shawarama, Biryani Combo, Rolls',
  'North Indian, Kebab, Chinese, Fast Food',
  '400',
  'Delivery',
  'Banashankari'],
 ['Gustoes Beer House',
  'No',
  'No',
  4.1,
  868,
  '080 49653521',
  'Banashankari',
  'Pub',
  'Beer, Wedges, Pizza, Nachos, Salads, Papaya Salad, Buffalo Wings',
  'Continental, Italian, Mexican, North Indian, Chinese, Steak',
  '1,200',
  'Delivery',
  'Banashankari'],
 ['The Biryani Cafe',
  'No',
  'No',
  4.1,
  520,
  '+91 7010846043',
  'Banashankari',
  'Quick Bites',
  'Vegetable Biryani, Ginger Chicken, Chicken Biryani, Donne Biryani, Chicken Kebab, Egg Bhurji, Dum Biryani',
  'Biryani, Chinese, Kebab',
  '300',
  'Delivery',
  'Banashankari'],
 ['Rolls On Wheels',
  'No',
  'No',
  3.6,
  299,
  '+91 9071734101\r\n+91 9071496800',
  'Banashankari',
  'Quick Bites',
  'Rolls, Momos, Fries, Veggie Roll, Chicken Kebab Roll, Paneer Roll, Cheese Roll',
  'Fast Food, Rolls, Momos',
  '300',
  'Delivery',
  'Banashankari'],
 ['Sri Guru Kottureshwara Davangere Benne Dosa',
  'Yes',
  'No',
  4.1,
  558,
  '+91 9448305384\r\n+91 9060079480',
  'Basavanagudi',
  'Quick Bites',
  'Benne Dosa, Mirchi Bajji, Filter Coffee, Poha, Tea, Butter Dosa, Crispy Dosa',
  'South Indian',
  '150',
  'Delivery',
  'Banashankari'],
 ['Upahar Sagar',
  'No',
  'No',
  3.8,
  39,
  '+91 9164571705\r\n080 26760336',
  'Banashankari',
  'Quick Bites',
  'Masala Dosa',
  'South Indian, Chinese, North Indian',
  '350',
  'Delivery',
  'Banashankari'],
 ['Frozen Bottle',
  'Yes',
  'No',
  4.2,
  146,
  '080 48664811',
  'Banashankari',
  'Beverage Shop',
  'Berryblast, Waffles, Cheesecake, Salted Caramel',
  'Beverages, Desserts, Ice Cream',
  '400',
  'Delivery',
  'Banashankari'],
 ['Meghana Foods',
  'Yes',
  'No',
  4.4,
  4401,
  '080 49653564',
  'Jayanagar',
  'Casual Dining',
  'Chicken Boneless Biryani, Hyderabadi Biryani, Paneer Biryani, Tandoori Chicken, Vegetable Biryani, Chicken Kebab, Raita',
  'Biryani, North Indian, Chinese',
  '600',
  'Delivery',
  'Banashankari'],
 ['Nandhini Deluxe',
  'No',
  'No',
  2.6,
  283,
  '080 26890011\r\n080 26890033',
  'Banashankari',
  'Casual Dining',
  'Biryani, Chicken Guntur, Thali, Buttermilk, Manchurian',
  'North Indian',
  '600',
  'Delivery',
  'Banashankari'],
 ["Vi Ra's Bar and Restaurant",
  'No',
  'No',
  3.3,
  62,
  '+91 9845063930\r\n+91 7411148111',
  'Banashankari',
  'Bar',
  'Chilli Chicken',
  'South Indian, North Indian, Chinese',
  '800',
  'Delivery',
  'Banashankari'],
 ['Chatar Patar',
  'No',
  'No',
  3.7,
  65,
  '+91 7619353103',
  'Banashankari',
  'Quick Bites',
  'Panipuri, Chaat, Noodles, Dahi Bhalle',
  'Fast Food, Street Food',
  '300',
  'Delivery',
  'Banashankari'],
 ['Polar Bear',
  'Yes',
  'No',
  3.8,
  71,
  '080 49652725',
  'Basavanagudi',
  'Dessert Parlor',
  'Hot Chocolate Fudge',
  'Ice Cream, Desserts, Beverages, Sandwich',
  '400',
  'Delivery',
  'Banashankari'],
 ["Kidambi's Kitchen",
  'No',
  'No',
  3.5,
  52,
  '080 42112211\r\n+91 9880412211',
  'Banashankari',
  'Quick Bites',
  'Rooftop Ambience',
  'South Indian',
  '300',
  'Delivery',
  'Banashankari'],
 ['Mane Thindi',
  'No',
  'No',
  3.7,
  130,
  '+91 9964410276',
  'Banashankari',
  'Quick Bites',
  'Coffee, Tea, Kesari Bath, Open Dosa, Vada, Idli, Bread Dosa',
  'South Indian',
  '200',
  'Delivery',
  'Banashankari'],
 ['Floured-Baked With Love',
  'No',
  'No',
  3.8,
  45,
  '+91 9845552266\n+91 9845552288',
  'Banashankari',
  'Takeaway, Delivery',
  'Cup Cake, Chocolate Cake',
  'Bakery',
  '400',
  'Delivery',
  'Banashankari'],
 ['Bengaluru Coffee House',
  'Yes',
  'No',
  4.1,
  201,
  '+91 9740180090',
  'Banashankari',
  'Quick Bites',
  'Masala Dosa, Tirupathi Pongal, Filter Coffee, Vada, Kharabath, Kali Dosa, Rava Idli',
  'South Indian, North Indian, Chinese, Street Food',
  '300',
  'Delivery',
  'Banashankari'],
 ['Anna Kuteera',
  'Yes',
  'No',
  4.0,
  771,
  '+91 9620009302',
  'Banashankari',
  'Casual Dining',
  'Panner Tikka, Kulfi, Coffee, Pav Bhaji, Carrot Halwa, Fried Rice, Set Dosa',
  'South Indian, North Indian, Chinese',
  '450',
  'Delivery',
  'Banashankari'],
 ['Darbar',
  'No',
  'No',
  3.0,
  98,
  '+91 8861271465',
  'Banashankari',
  'Bar',
  'Paneer Tikka, Dal Kichadi, French Fries',
  'North Indian, Chinese',
  '800',
  'Delivery',
  'Banashankari'],
 ['Sri Udupi Food Hub',
  'Yes',
  'Yes',
  4.1,
  175,
  '+91 9916866033',
  'Jayanagar',
  'Casual Dining',
  'Filter Coffee, Masala Dosa, Idli, Vada',
  'South Indian, North Indian, Chinese, Beverages',
  '500',
  'Delivery',
  'Banashankari'],
 ['House Of Kebabs',
  'Yes',
  'No',
  3.8,
  540,
  '080 49653042',
  'Basavanagudi',
  'Casual Dining',
  'Rolls, Shawarma, Butter Chicken, Mutton Biryani, Lahori Chicken, Chicken Roll, Grape Juice',
  'North Indian, Kebab, Biryani, Chinese',
  '650',
  'Delivery',
  'Banashankari'],
 ['Roll N Rock',
  'Yes',
  'No',
  3.8,
  124,
  '+91 9590941992',
  'Kumaraswamy Layout',
  'Quick Bites',
  'Rolls, Paratha, Chicken Biryani',
  'Chinese, North Indian, Mughlai, Rolls',
  '400',
  'Delivery',
  'Banashankari'],
 ['BOX8- Desi Meals',
  'Yes',
  'No',
  4.1,
  340,
  '022 33552698',
  'Banashankari',
  'Takeaway, Delivery',
  'Paratha, Mughlai Chicken, Masala Lemonade, Butter Chicken, Rajma, Sandwich, Salad',
  'North Indian, Mughlai, Fast Food',
  '500',
  'Delivery',
  'Banashankari'],
 ['KFC',
  'Yes',
  'No',
  3.8,
  505,
  '080 33994444',
  'Banashankari',
  'Quick Bites',
  'Burgers, French Fries',
  'Burger, Fast Food',
  '450',
  'Delivery',
  'Banashankari'],
 ['Roll Over',
  'Yes',
  'No',
  4.1,
  438,
  '+91 8884942976\r\n+91 8884942900',
  'Jayanagar',
  'Dessert Parlor',
  'Rolls, Ice Cream Roll, Paan Ice Cream, Coffee, Vanilla Ice Cream, Chocolate Icecreams, Mississippi Mudpie',
  'Desserts, Ice Cream, Beverages, Fast Food, Sandwich',
  '500',
  'Delivery',
  'Banashankari'],
 ['Imperial Restaurant',
  'Yes',
  'No',
  3.7,
  264,
  '+91 7338431313\r\n080 26741313',
  'Mysore Road',
  'Casual Dining',
  'Kadhai Paneer, Ghee Rice, Chicken Grill, Shawarma, Paratha, Biryani, Butter Chicken',
  'North Indian, Chinese, Biryani, Beverages',
  '750',
  'Delivery',
  'Banashankari'],
 ['Wahab',
  'Yes',
  'No',
  3.7,
  97,
  '+91 9845088001',
  'Jayanagar',
  'Quick Bites',
  'Chicken Biryani, Rolls',
  'North Indian, Mughlai, Chinese',
  '350',
  'Delivery',
  'Banashankari'],
 ['Canton',
  'Yes',
  'No',
  3.6,
  195,
  '080 41410069\r\n+91 9611320069',
  'Jayanagar',
  'Casual Dining',
  'Roast Pork, Tai Pai Chicken, Beer, Sweet Corn Chicken Soup, Masala Peanuts, Chinese Chop Suey, Chicken Lollipop',
  'Chinese, Seafood, Biryani',
  '800',
  'Delivery',
  'Banashankari'],
 ['The Blue Wagon - Kitchen',
  'Yes',
  'No',
  4.6,
  228,
  '+91 8105485007\r\n+91 8095904280',
  'Jayanagar',
  'Cafe',
  'Pizza, Nachos, Garlic Maggi, Burgers, Cheese Maggi, Bruschetta Bites, Sandwich',
  'Cafe, Beverages',
  '400',
  'Delivery',
  'Banashankari'],
 ['Patio 805',
  'Yes',
  'Yes',
  4.1,
  364,
  '+91 8884999805',
  'Jayanagar',
  'Casual Dining',
  'Noodles, Laksa Soup, Coffee, Veg Fritters, Vegetarian, Babycorn Manchurian, Mango Salad',
  'Thai, Vietnamese, Asian, Chinese',
  '1,200',
  'Delivery',
  'Banashankari'],
 ['Lassi Corner',
  'Yes',
  'No',
  3.7,
  107,
  '+91 9972348689\r\n+91 7204756477',
  'Basavanagudi',
  'Beverage Shop',
  'Lassi',
  'Beverages, Ice Cream',
  '150',
  'Delivery',
  'Banashankari'],
 ['Sagar Deluxe',
  'Yes',
  'No',
  3.2,
  167,
  '080 32963232\r\n+91 9620284767',
  'Kumaraswamy Layout',
  'Quick Bites',
  'Coffee, Chaat',

In [ ]:
# Create a table

mycursor.execute("""CREATE TABLE if not EXISTS Restaurant_Data (

                 name VARCHAR(100) NOT NULL,
                 online_order VARCHAR(50),
                 book_table VARCHAR(50),
                 rate DECIMAL(3,1),
                 votes INT,
                 phone VARCHAR (50),
                 location VARCHAR(100),
                 rest_type VARCHAR(100),
                 dish_liked TEXT,
                 cuisines VARCHAR(300),
                 approx_cost DECIMAL(10,2),
                 listed_type VARCHAR(100),
                 listed_city VARCHAR (100)

                 )""")
conn.commit()

In [ ]:
# Insert data into table

query = """INSERT INTO Restaurant_Data
(name, online_order, book_table, rate, votes,
phone, location, rest_type, dish_liked, cuisines,
approx_cost, listed_type, listed_city)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"""

mycursor.executemany(query,data)
conn.commit()

In [ ]:
# Select entire data

import pandas as pd

query = "SELECT * FROM Restaurant_Data"
df = pd.read_sql_query(query, conn)
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost,listed_type,listed_city
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23153,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23154,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23155,Keys Cafe - Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23156,Bhagini,No,No,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23157,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

In [ ]:
# Applying filters for the given data

query = """SELECT *
FROM Restaurant_Data
WHERE
online_order = 'Yes' AND
rest_type = 'Delivery' AND
approx_cost < 500 AND
votes < 400 AND
listed_type = 'Delivery'
"""
df = pd.read_sql_query(query, conn)
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost,listed_type,listed_city
0,Mealer.in,Yes,No,4.0,205,080 48542046\r\r\n+91 9513771133,JP Nagar,Delivery,"Rajma, Dal Makhani, Kadhi Chawal, Dal Tadka","North Indian, Biryani",450,Delivery,Bannerghatta Road
1,Calorie Express,Yes,No,3.6,192,+91 9663868626,BTM,Delivery,Chicken Sandwich,Healthy Food,450,Delivery,Bannerghatta Road
2,Rithika's Kitchen,Yes,No,3.8,106,+91 9901468279\r\r\n+91 8904588050,JP Nagar,Delivery,"Mutton Curry, Chicken Fry, Chicken Biryani, Ch...","Biryani, South Indian, Andhra",350,Delivery,Bannerghatta Road
3,Dream a Dozen,Yes,No,4.3,133,+91 8861739269,JP Nagar,Delivery,"Cup Cake, Cake Pops, Chocolate Truffle Cake, B...","Bakery, Desserts",300,Delivery,Bannerghatta Road
4,FreshMenu,Yes,No,3.2,113,080 40424242,Marathahalli,Delivery,"Biryani, Burgers","Healthy Food, Chinese, Biryani, North Indian, ...",450,Delivery,Bellandur
...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,Bonfooder,Yes,No,3.8,36,+91 8884532555,Sarjapur Road,Delivery,"Dahi Bhalle, Thali",North Indian,400,Delivery,Sarjapur Road
177,Kerala Tiffin,Yes,No,3.9,167,+91 7907943091,Whitefield,Delivery,Appam,Kerala,300,Delivery,Whitefield
178,Techies Kitchen,Yes,No,3.5,197,+91 9880329528,"ITPL Main Road, Whitefield",Delivery,"Chicken Biryani, Aloo Paratha","Biryani, North Indian",400,Delivery,Whitefield
179,KA53,Yes,No,3.9,45,080 49652151,Whitefield,Delivery,"Paneer Pasanda, Panneer Butter Masala, Murgh P...","North Indian, Chinese",300,Delivery,Whitefield
180,Office Lunch Box,Yes,No,3.6,114,+91 7338220909\n+91 7338220808,Whitefield,Delivery,Chicken Curry,"Andhra, North Indian",200,Delivery,Whitefield

In [ ]:
# 1. Which Bangalore locations have the highest average restaurant ratings?

query = """SELECT
location, AVG(rate) as AVG_Rating
FROM Restaurant_Data
GROUP BY location
ORDER BY AVG_Rating DESC
LIMIT 15
"""
df = pd.read_sql_query(query, conn)
df

                 location  AVG_Rating
0            Lavelle Road    4.192534
1   Koramangala 5th Block    4.151507
2             Sankey Road    4.105882
3   Koramangala 3rd Block    4.101242
4         Cunningham Road    4.100300
5          St. Marks Road    4.099013
6   Koramangala 2nd Block    4.073333
7          Sadashiv Nagar    4.055263
8          Residency Road    4.051364
9           Church Street    4.045455
10  Koramangala 4th Block    4.044146
11          Seshadripuram    4.031884
12          Richmond Road    4.029060
13                 Ulsoor    4.021186
14            Koramangala    4.011765

In [ ]:
# 2. Which locations are over-saturated with restaurants?

query = """SELECT
location, count(name) as Restaurant_count
From Restaurant_Data
Group by location
Order by Restaurant_count DESC
LIMIT 15
"""
df=pd.read_sql_query(query,conn)
df

                 location  Restaurant_count
0   Koramangala 5th Block              1782
1                     BTM              1454
2             Indiranagar              1346
3                     HSR              1161
4               Jayanagar              1037
5                JP Nagar              1016
6              Whitefield               824
7   Koramangala 7th Block               723
8   Koramangala 6th Block               718
9            Marathahalli               680
10  Koramangala 4th Block               644
11                MG Road               595
12           Brigade Road               567
13          Church Street               506
14      Bannerghatta Road               496

In [ ]:
# 3. Does online ordering improve restaurant ratings?

query = """SELECT
online_order, AVG(rate) as Restaurant_Rating
FROM Restaurant_Data
Group by Online_order
Order by Restaurant_Rating DESC
"""
df = pd.read_sql_query(query,conn)
df

  online_order  Restaurant_Rating
0           No           3.929549
1          Yes           3.893425

In [ ]:
# 4. Does table booking correlate with higher customer ratings?

query = """SELECT
book_table, AVG(rate) as Restaurant_Rating
FROM Restaurant_Data
Group by book_table
Order by Restaurant_Rating DESC
"""
df = pd.read_sql_query(query,conn)
df

  book_table  Restaurant_Rating
0        Yes           4.160189
1         No           3.813219

In [ ]:
# 5. What price range delivers the best customer satisfaction?

query = """SELECT
approx_cost, AVG(rate) as Restaurant_Rating
FROM Restaurant_Data
Group by approx_cost
order by Restaurant_Rating DESC
LIMIT 15
"""
df = pd.read_sql_query(query,conn)
df

   approx_cost  Restaurant_Rating
0        2,700           4.500000
1        3,200           4.400000
2          120           4.400000
3        1,600           4.337447
4        3,500           4.328000
5        1,250           4.325000
6        6,000           4.300000
7        5,000           4.300000
8        4,500           4.300000
9        1,650           4.300000
10       3,400           4.300000
11       2,800           4.287097
12       1,700           4.281223
13       4,000           4.258333
14       1,400           4.236842

In [ ]:
# 6. Which cuisines are most common in Bangalore?

query = """SELECT
cuisines, count(name) as Restaurant_count
FROM Restaurant_Data
Group by cuisines
order by Restaurant_count DESC
LIMIT 15
"""
df = pd.read_sql_query(query,conn)
df

                               cuisines  Restaurant_count
0                          North Indian              1144
1                 North Indian, Chinese               776
2                          South Indian               359
3                                  Cafe               273
4   South Indian, North Indian, Chinese               233
5                      Bakery, Desserts               215
6                   Desserts, Beverages               214
7                               Chinese               210
8                   Ice Cream, Desserts               208
9                              Desserts               206
10                              Biryani               169
11                       Chinese, Momos               162
12                          Finger Food               151
13                            Fast Food               150
14       North Indian, Chinese, Biryani               138

In [ ]:
# 7. Which cuisines receive the highest average ratings?  check

query = """SELECT
cuisines, AVG(rate) as AVG_Restaurant_Rating
FROM Restaurant_Data
WHERE cuisines LIKE '%American%'
Group by cuisines
order by AVG_Restaurant_Rating DESC
LIMIT 20
"""
df = pd.read_sql_query(query,conn)
df

                                             cuisines  AVG_Restaurant_Rating
0             American, Tex-Mex, Burger, BBQ, Mexican               4.750000
1                            Italian, American, Pizza               4.700000
2   Chinese, American, Continental, Italian, North...               4.700000
3   American, Continental, North Indian, Mediterra...               4.650000
4                              Cafe, American, Burger               4.600000
5                   Cafe, American, Burger, Beverages               4.600000
6                       American, North Indian, Salad               4.600000
7        American, North Indian, Chinese, Finger Food               4.600000
8                       Cafe, American, Burger, Steak               4.595349
9        Continental, North Indian, Chinese, American               4.566667
10                     American, Tex-Mex, Burger, BBQ               4.550000
11  Continental, North Indian, Chinese, American, ...               4.500000
12  Continental, American, Italian, Modern Indian,...               4.500000
13                       American, Continental, Salad               4.500000
14         American, Continental, North Indian, Salad               4.500000
15                              American, Continental               4.500000
16  American, Cafe, Continental, French, Burger, M...               4.500000
17                                      American, BBQ               4.500000
18                  Modern Indian, European, American               4.450000
19                       American, Continental, Pizza               4.450000

In [ ]:
# 8. Which cuisines perform well despite having fewer restaurants?

query = """SELECT
cuisines, count(name) as Restaurant_Count, AVG(rate) as AVG_Restaurant_Rating
FROM Restaurant_Data
WHERE cuisines LIKE '%Andhra%' and cuisines Like '%Biryani%'
Group by cuisines
order by Restaurant_Count
LIMIT 20
"""

df = pd.read_sql_query(query,conn)
df

,cuisines,Restaurant_Count,AVG_Restaurant_Rating
0,"Andhra, Chinese, Biryani",1,2.600000
1,"Andhra, Hyderabadi, Biryani",1,3.700000
2,"Andhra, North Indian, Biryani, Seafood",1,3.900000
3,"Biryani, Mughlai, Andhra",1,4.600000
4,"Hyderabadi, Andhra, Chinese, Biryani",1,4.000000
5,"Andhra, North Indian, Chinese, Biryani, Seafood",2,3.800000
6,"Biryani, Chinese, Andhra",2,3.800000
7,"Biryani, South Indian, North Indian, Chinese, ...",2,3.700000
8,"Continental, Biryani, Pizza, North Indian, Chi...",2,3.700000
9,"South Indian, Andhra, Biryani",2,3.700000
10,"Andhra, North Indian, Chinese, Seafood, Biryani",3,3.666667
11,"Biryani, Hyderabadi, Andhra, North Indian",3,3.800000
12,"Biryani, North Indian, Seafood, Andhra",3,3.900000
13,"Biryani, South Indian, Andhra",3,3.800000
14,"Chinese, South Indian, Andhra, North Indian, B...",3,3.100000
15,"Andhra, Biryani, Chinese, Hyderabadi, North In...",4,4.000000
16,"Andhra, Biryani, Seafood, North Indian",4,3.875000
17,"Andhra, Hyderabadi, Biryani, Chinese, North In...",4,4.100000
18,"Andhra, North Indian, Biryani, Beverages",4,3.750000
19,"Andhra, South Indian, Biryani",4,3.325000

In [ ]:
# 9. What is the relationship between restaurant cost and rating?

query = """SELECT
approx_cost, AVG(rate) as AVG_Restaurant_Rating
FROM Restaurant_Data
Group by approx_cost
order by AVG_Restaurant_Rating DESC
LIMIT 15
"""
df=pd.read_sql_query(query,conn)
df

   approx_cost  AVG_Restaurant_Rating
0        2,700               4.500000
1        3,200               4.400000
2          120               4.400000
3        1,600               4.337447
4        3,500               4.328000
5        1,250               4.325000
6        6,000               4.300000
7        5,000               4.300000
8        4,500               4.300000
9        1,650               4.300000
10       3,400               4.300000
11       2,800               4.287097
12       1,700               4.281223
13       4,000               4.258333
14       1,400               4.236842

In [ ]:
# 10. Do restaurants offering both online ordering and table booking perform better?

query = """SELECT
online_order, book_table, AVG(rate) as AVG_Restaurant_Rating
FROM Restaurant_Data
Group by online_order, book_table
order by AVG_Restaurant_Rating DESC
"""
df = pd.read_sql_query(query,conn)
df

  online_order book_table  AVG_Restaurant_Rating
0           No        Yes               4.182135
1          Yes        Yes               4.145573
2          Yes         No               3.821445
3           No         No               3.789171

In [ ]:
# 11. Which locations are ideal for premium restaurant onboarding?

query = """SELECT
location, Avg(rate) as AVG_Restaurant_Rating
FROM Restaurant_Data
Group by location
order by AVG_Restaurant_Rating DESC
LIMIT 15
"""
df = pd.read_sql_query(query,conn)
df

                 location  AVG_Restaurant_Rating
0            Lavelle Road               4.192534
1   Koramangala 5th Block               4.151507
2             Sankey Road               4.105882
3   Koramangala 3rd Block               4.101242
4         Cunningham Road               4.100300
5          St. Marks Road               4.099013
6   Koramangala 2nd Block               4.073333
7          Sadashiv Nagar               4.055263
8          Residency Road               4.051364
9           Church Street               4.045455
10  Koramangala 4th Block               4.044146
11          Seshadripuram               4.031884
12          Richmond Road               4.029060
13                 Ulsoor               4.021186
14            Koramangala               4.011765

In [ ]:
# Adding and Reading json file

df1=pd.read_json("orders.json")
df1

FileNotFoundError: File orders.json does not exist

In [ ]:
df1.columns

In [ ]:
data=df1.values.tolist()
data

In [ ]:
# create a table

mycursor.execute("""
CREATE TABLE if not EXISTS Orders (
                 order_id INTEGER PRIMARY KEY AUTOINCREMENT,
                 restaurant_name VARCHAR(100) NOT NULL,
                 order_date VARCHAR(50),
                 order_value DECIMAL(3,1),
                 discount_used VARCHAR (50),
                 payment_method VARCHAR (50)
                 )""")
conn.commit()

In [ ]:
# Insert data into table

query = """
INSERT INTO Orders
(restaurant_name, order_date, order_value,
 discount_used, payment_method)
VALUES (?, ?, ?, ?, ?)
"""

data = df1[['restaurant_name',
            'order_date',
            'order_value',
            'discount_used',
            'payment_method']].values.tolist()

mycursor.executemany(query, data)
conn.commit()

In [ ]:
df1.drop_duplicates()

In [ ]:
# 1. What is the total order_value on order_date 2026-01-22?

query = """SELECT
order_date, sum(order_value) as Total_Order_Value
FROM Orders
WHERE order_date = '2026-01-22'
"""
df1 = pd.read_sql_query(query,conn)
df1

In [ ]:
# 2. What is the relationship between order_value and discount_used?

query = """SELECT
discount_used, AVG(order_value) as AVG_Order_Value
FROM Orders
Group by discount_used
order by AVG_order_value DESC
"""

df1 = pd.read_sql_query(query,conn)
df1

In [ ]:
# 3. Most used payment method?

query = """SELECT
payment_method, count(payment_method) as Payment_Method_Count
FROM Orders
Group by payment_method
order by Payment_Method_Count
"""

df1 = pd.read_sql_query(query,conn)
df1

In [ ]:
# 4. will discount increase order value?

query = """SELECT
discount_used, AVG(order_value) as AVG_Order_Value
FROM Orders
Group by discount_used
order by AVG_order_value DESC
"""

df1 = pd.read_sql_query(query,conn)
df1

In [ ]:
# 5. Which restaurant generates highest revenue?

query = """SELECT
restaurant_name, sum(order_value) as Total_Revenue
FROM Orders
Group by restaurant_name
order by Total_Revenue DESC
LIMIT 16
"""

df1 = pd.read_sql_query(query,conn)
df1

In [ ]:
# 6. Which date had highest revenue?

query = """SELECT
order_date, sum(order_value) as Revenue
From orders
Group by order_date
order by Revenue DESC
LIMIT 10
"""

df1 = pd.read_sql_query(query,conn)
df1

In [ ]:
# 7. on which order_date discounts are used the most?

query = """SELECT
order_date, count(discount_used) as Total_Discounts
FROM orders
GROUP BY order_date
ORDER BY Total_Discounts DESC
LIMIT 15
"""

df1 = pd.read_sql_query(query,conn)
df1

In [ ]:
# 8. what is the order date where highest no:of orders taken place in restaurant?

query = """SELECT
order_date, restaurant_name, count(restaurant_name) as Highest_orders
FROM orders
group by order_date, restaurant_name
order by Highest_orders DESC
limit 20
"""

df1 = pd.read_sql_query(query,conn)
df1